events {}

http {
    server {
        listen 80;
        location / {
          proxy_pass http://tomcat:8080/laboratory-04/;
        }
    }
}
#Modificación para implemntar el servlet de consumo de BD en postgresl
#            proxy_pass http://tomcat:8080;